// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.3
// source: trx.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import {
  GetBatteryStatus_Request,
  GetBatteryStatus_Response,
  GetDeviceInfo_Request,
  GetDeviceInfo_Response,
} from "./trx.device";
import { SetEntity_Request, SetEntity_Response } from "./trx.tracker";

export interface Request {
  /** Device */
  getBatteryStatus?: GetBatteryStatus_Request | undefined;
  getDeviceInfo?:
    | GetDeviceInfo_Request
    | undefined;
  /** Tracker */
  setEntity?: SetEntity_Request | undefined;
}

export interface Response {
  /** Device */
  getBatteryStatus?: GetBatteryStatus_Response | undefined;
  getDeviceInfo?:
    | GetDeviceInfo_Response
    | undefined;
  /** Tracker */
  setEntity?: SetEntity_Response | undefined;
}

export interface Error {
  type: string;
  message: string;
}

export interface TrxMessage {
  id: string;
  request?: Request | undefined;
  response?: Response | undefined;
  error?: Error | undefined;
}

function createBaseRequest(): Request {
  return { getBatteryStatus: undefined, getDeviceInfo: undefined, setEntity: undefined };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getBatteryStatus !== undefined) {
      GetBatteryStatus_Request.encode(message.getBatteryStatus, writer.uint32(10).fork()).ldelim();
    }
    if (message.getDeviceInfo !== undefined) {
      GetDeviceInfo_Request.encode(message.getDeviceInfo, writer.uint32(18).fork()).ldelim();
    }
    if (message.setEntity !== undefined) {
      SetEntity_Request.encode(message.setEntity, writer.uint32(82).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getBatteryStatus = GetBatteryStatus_Request.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.getDeviceInfo = GetDeviceInfo_Request.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.setEntity = SetEntity_Request.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getBatteryStatus: isSet(object.getBatteryStatus)
        ? GetBatteryStatus_Request.fromJSON(object.getBatteryStatus)
        : undefined,
      getDeviceInfo: isSet(object.getDeviceInfo) ? GetDeviceInfo_Request.fromJSON(object.getDeviceInfo) : undefined,
      setEntity: isSet(object.setEntity) ? SetEntity_Request.fromJSON(object.setEntity) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getBatteryStatus !== undefined) {
      obj.getBatteryStatus = GetBatteryStatus_Request.toJSON(message.getBatteryStatus);
    }
    if (message.getDeviceInfo !== undefined) {
      obj.getDeviceInfo = GetDeviceInfo_Request.toJSON(message.getDeviceInfo);
    }
    if (message.setEntity !== undefined) {
      obj.setEntity = SetEntity_Request.toJSON(message.setEntity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getBatteryStatus = (object.getBatteryStatus !== undefined && object.getBatteryStatus !== null)
      ? GetBatteryStatus_Request.fromPartial(object.getBatteryStatus)
      : undefined;
    message.getDeviceInfo = (object.getDeviceInfo !== undefined && object.getDeviceInfo !== null)
      ? GetDeviceInfo_Request.fromPartial(object.getDeviceInfo)
      : undefined;
    message.setEntity = (object.setEntity !== undefined && object.setEntity !== null)
      ? SetEntity_Request.fromPartial(object.setEntity)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { getBatteryStatus: undefined, getDeviceInfo: undefined, setEntity: undefined };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getBatteryStatus !== undefined) {
      GetBatteryStatus_Response.encode(message.getBatteryStatus, writer.uint32(10).fork()).ldelim();
    }
    if (message.getDeviceInfo !== undefined) {
      GetDeviceInfo_Response.encode(message.getDeviceInfo, writer.uint32(18).fork()).ldelim();
    }
    if (message.setEntity !== undefined) {
      SetEntity_Response.encode(message.setEntity, writer.uint32(82).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getBatteryStatus = GetBatteryStatus_Response.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.getDeviceInfo = GetDeviceInfo_Response.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.setEntity = SetEntity_Response.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      getBatteryStatus: isSet(object.getBatteryStatus)
        ? GetBatteryStatus_Response.fromJSON(object.getBatteryStatus)
        : undefined,
      getDeviceInfo: isSet(object.getDeviceInfo) ? GetDeviceInfo_Response.fromJSON(object.getDeviceInfo) : undefined,
      setEntity: isSet(object.setEntity) ? SetEntity_Response.fromJSON(object.setEntity) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.getBatteryStatus !== undefined) {
      obj.getBatteryStatus = GetBatteryStatus_Response.toJSON(message.getBatteryStatus);
    }
    if (message.getDeviceInfo !== undefined) {
      obj.getDeviceInfo = GetDeviceInfo_Response.toJSON(message.getDeviceInfo);
    }
    if (message.setEntity !== undefined) {
      obj.setEntity = SetEntity_Response.toJSON(message.setEntity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.getBatteryStatus = (object.getBatteryStatus !== undefined && object.getBatteryStatus !== null)
      ? GetBatteryStatus_Response.fromPartial(object.getBatteryStatus)
      : undefined;
    message.getDeviceInfo = (object.getDeviceInfo !== undefined && object.getDeviceInfo !== null)
      ? GetDeviceInfo_Response.fromPartial(object.getDeviceInfo)
      : undefined;
    message.setEntity = (object.setEntity !== undefined && object.setEntity !== null)
      ? SetEntity_Response.fromPartial(object.setEntity)
      : undefined;
    return message;
  },
};

function createBaseError(): Error {
  return { type: "", message: "" };
}

export const Error = {
  encode(message: Error, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Error {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Error {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.type = object.type ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseTrxMessage(): TrxMessage {
  return { id: "", request: undefined, response: undefined, error: undefined };
}

export const TrxMessage = {
  encode(message: TrxMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.request !== undefined) {
      Request.encode(message.request, writer.uint32(18).fork()).ldelim();
    }
    if (message.response !== undefined) {
      Response.encode(message.response, writer.uint32(26).fork()).ldelim();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TrxMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrxMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.request = Request.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.response = Response.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TrxMessage {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      request: isSet(object.request) ? Request.fromJSON(object.request) : undefined,
      response: isSet(object.response) ? Response.fromJSON(object.response) : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: TrxMessage): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.request !== undefined) {
      obj.request = Request.toJSON(message.request);
    }
    if (message.response !== undefined) {
      obj.response = Response.toJSON(message.response);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrxMessage>, I>>(base?: I): TrxMessage {
    return TrxMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrxMessage>, I>>(object: I): TrxMessage {
    const message = createBaseTrxMessage();
    message.id = object.id ?? "";
    message.request = (object.request !== undefined && object.request !== null)
      ? Request.fromPartial(object.request)
      : undefined;
    message.response = (object.response !== undefined && object.response !== null)
      ? Response.fromPartial(object.response)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
